(function(root){'use strict';
const chart=[[242,'39 1/3',6,6.5],[246,'40',6.5,7],[250,'40 2/3',7,7.5],[255,'41 1/3',7.5,8],[259,'42',8,8.5],[263,'42 2/3',8.5,9],[267,'43 1/3',9,9.5],[271,'44',9.5,10],[276,'44 2/3',10,10.5],[280,'45 1/3',10.5,11],[284,'46',11,11.5],[288,'46 2/3',11.5,12],[293,'47 1/3',12,12.5]];
function number(v,min=0,max=100000000,integer=false){if(v===''||v==null)throw Error('빈칸 없이 값을 입력해 주세요.');const n=Number(v);if(!Number.isFinite(n)||n<min||n>max||(integer&&!Number.isInteger(n)))throw Error('입력 범위와 정수 여부를 확인해 주세요.');return n;}
function calculate(kind,v){
 if(kind==='boot-size'){const n=Math.max(number(v.left,242,293),number(v.right,242,293));const exact=chart.find(r=>r[0]===n);const rows=exact?[exact]:[chart.filter(r=>r[0]<n).at(-1),chart.find(r=>r[0]>n)];return '큰 발 길이 '+n+'mm 기준\n'+rows.map(r=>r[0]+'mm → EU '+r[1]+' · UK '+r[2]+' · US 남성 '+r[3]).join('\n')+'\n'+(exact?'공식 표의 같은 길이 행입니다.':'두 표기 사이입니다. 자동으로 올림하거나 구매 사이즈를 확정하지 않습니다.')+'\n아디다스 성인 신발 표 기준입니다. 제품별 안내와 착화감을 확인하세요.';}
 if(kind==='winrate'){const w=number(v.w,0,10000,true),d=number(v.d,0,10000,true),l=number(v.l,0,10000,true),n=w+d+l;if(!n)throw Error('최소 한 경기의 기록을 입력해 주세요.');return n+'경기 · '+w+'승 '+d+'무 '+l+'패\n승률 '+(100*w/n).toFixed(1)+'%\n승점 '+(w*3+d)+'점 · 경기당 승점 '+((w*3+d)/n).toFixed(2)+'\n무승부는 승률의 승리 횟수에 포함하지 않습니다.';}
 if(kind==='points-sim'){const c=number(v.current,0,10000,true),r=number(v.remaining,0,100,true),t=number(v.target,0,10000,true);if(t<=c)return '목표 승점에 이미 도달했습니다. 순위 확정을 뜻하지는 않습니다.';if(c+r*3<t)return '전승해도 '+(c+r*3)+'점으로 목표에 도달하지 못합니다.';let out=[];for(let w=0;w<=r;w++){const d=Math.max(0,t-c-3*w);if(w+d<=r)out.push(w+'승 '+d+'무 '+(r-w-d)+'패 → '+(c+w*3+d)+'점');}return '목표 이상을 만드는 조합 (승리 수별 최소 무승부)\n'+out.join('\n')+'\n승 3점·무 1점·패 0점 기준. 다른 팀 결과·승점 삭감·동률 규정은 반영하지 않습니다.';}
 if(kind==='trip-cost'){const flight=number(v.flight),room=number(v.room),nights=number(v.nights,0,365,true),people=number(v.people,1,20,true),ticket=number(v.ticket),daily=number(v.daily),days=number(v.days,1,366,true),buffer=number(v.buffer,0,100);const base=flight+room*nights/people+ticket+daily*days,total=base*(1+buffer/100);return '1인 기본 예산 '+Math.round(base).toLocaleString('ko-KR')+'원\n예비비 '+buffer+'% 포함 '+Math.round(total).toLocaleString('ko-KR')+'원\n1인 숙박비 '+Math.round(room*nights/people).toLocaleString('ko-KR')+'원\n입력 금액을 계산한 결과이며 실제 시세나 환율 조회값은 아닙니다.';}
}
function kickoff(date,time,tz){if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))throw Error('현지 날짜와 시간을 입력해 주세요.');const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number),wall=Date.UTC(y,m-1,d,h,min),check=new Date(wall);if(check.getUTCMonth()!==m-1||check.getUTCDate()!==d||h>23||min>59)throw Error('유효한 날짜와 시간을 입력해 주세요.');const f=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});const parts=t=>{const p=Object.fromEntries(f.formatToParts(new Date(t)).map(p=>[p.type,p.value]));return Date.UTC(+p.year,+p.month-1,+p.day,+p.hour,+p.minute);};const offsets=new Set();for(let k=-36;k<=36;k+=3){const t=wall+k*3600000;offsets.add(parts(t)-t);}const matches=[...offsets].map(off=>wall-off).filter(t=>parts(t)===wall).sort((a,b)=>a-b);if(!matches.length)throw Error('서머타임 전환으로 존재하지 않는 현지 시간입니다. 공식 일정의 시간대를 다시 확인하세요.');const fmt=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});return (matches.length>1?'현지 시간이 두 번 존재합니다. 공식 일정의 UTC 오프셋 확인이 필요합니다.\n':'한국시간\n')+matches.map(t=>fmt.format(new Date(t))).join('\n');}
const api={calculate,kickoff,chart};if(typeof module==='object'&&module.exports){module.exports=api;return;}root.ReaderTools=api;const form=document.querySelector('#calculator');if(!form)return;const kind=document.body.dataset.tool,result=document.querySelector('#result');form.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(form));try{result.textContent=kind==='kickoff'?kickoff(v.date,v.time,v.zone):calculate(kind,v);}catch(err){result.textContent=err.message;}result.hidden=false;});document.querySelector('#sample').addEventListener('click',()=>{Object.entries(JSON.parse(form.dataset.sample)).forEach(([key,value])=>form.elements.namedItem(key).value=value);form.requestSubmit();});form.addEventListener('input',()=>{result.hidden=true;});
})(typeof globalThis!=='undefined'?globalThis:this);
