from pathlib import Path
import html, json
ROOT=Path(__file__).resolve().parent.parent
SOURCE=Path(__file__).parent
def heading(t): return '<h2>'+t+'</h2>'
def p(t): return '<p>'+t+'</p>'
uniform='''<h1>유니폼 사이즈 비교 — 내 옷 실측으로 확인하기</h1><p class="lead">잘 맞는 옷과 구매할 유니폼의 가슴 단면·총장을 비교하세요. 두 옷의 치수 차이를 cm로 보여드립니다.</p>
<section class="tool-panel" aria-labelledby="compare-title"><h2 id="compare-title">두 옷의 실측 비교</h2><p class="hint">모든 값은 의류를 평평하게 놓고 잰 cm 단위입니다. 신체 가슴둘레를 넣지 마세요.</p><form id="compare"><div class="fields">'''
for ident,label in [('own-width','내 옷 가슴 단면'),('own-length','내 옷 총장'),('new-width','구매할 옷 가슴 단면'),('new-length','구매할 옷 총장')]:
 uniform+=f'<div class="field"><label for="{ident}">{label} (cm)</label><input id="{ident}" type="number" min="0.1" max="200" step="0.1" required inputmode="decimal"></div>'
uniform+='''</div><div class="actions"><button type="submit">실측 차이 비교하기</button><button type="button" class="secondary" id="sample">예시 넣기</button></div></form><p id="result" class="result" role="status" hidden></p></section>
<h2>가슴둘레와 가슴 단면은 다릅니다</h2><p>신체 가슴둘레는 몸의 가슴을 한 바퀴 잰 길이입니다. 의류 가슴 단면은 옷을 평평하게 펼쳤을 때 양쪽 겨드랑이 아래 사이의 폭입니다. 이 도구에는 <strong>의류의 단면 치수</strong>를 입력하세요. 브랜드 표가 신체 치수를 안내한다면 이 비교기에 그대로 입력하지 않습니다.</p>
<svg class="measure" viewBox="0 0 440 320" role="img" aria-label="옷을 펼쳐 양쪽 겨드랑이 아래를 가로로 측정하면 가슴 단면, 어깨의 높은 지점에서 밑단까지 재면 총장입니다"><path d="M140 45L80 85L110 135L140 120V285H300V120L330 135L360 85L300 45L255 30Q220 70 185 30Z" fill="#edf6ef" stroke="#205e40" stroke-width="3"/><path d="M145 145H295M275 55V280" stroke="#9a6916" stroke-width="3" stroke-dasharray="6 4"/><text x="158" y="138" fill="#17432c" font-size="18">가슴 단면 ↔</text><text x="290" y="210" fill="#17432c" font-size="18">총장 ↕</text></svg>
<h2>같은 방법으로 측정해야 비교할 수 있어요</h2><ol><li>평소 잘 맞는 티셔츠나 유니폼을 고르고 주름을 펴서 평평하게 놓습니다.</li><li>옷을 늘리지 않은 상태에서 가슴 단면과 총장을 잽니다. 위 그림은 측정 위치의 예시입니다.</li><li>판매자가 안내한 측정 시작점·끝점이 같은지 확인합니다. 총장을 뒷목부터 재는 상품과 어깨부터 재는 상품은 직접 비교하기 어렵습니다.</li><li>상품의 의류 실측표에서 후보 사이즈의 값을 가져와 비교합니다.</li></ol>
<h2>결과를 읽는 예시</h2><div class="example"><p>가상의 내 옷: 가슴 단면 52cm, 총장 70cm<br>가상의 후보: 가슴 단면 54cm, 총장 72cm<br><strong>결과: 단면과 총장이 각각 2cm 큽니다.</strong></p></div><p>이는 옷이 얼마나 큰지를 비교하는 값입니다. 몸에 2cm의 여유가 생긴다는 의미는 아닙니다. 어깨·소매·밑단 형태, 소재의 신축성, 이너 착용 여부에 따라 실제 느낌이 달라집니다.</p>
<h2>주문 전에 확인할 세 가지</h2><ul><li><strong>핏:</strong> 지금 옷처럼 입을지, 안에 옷을 더 입을지 먼저 정하세요.</li><li><strong>상품 버전:</strong> 같은 팀 유니폼이라도 상품별 핏·실측표가 다를 수 있습니다.</li><li><strong>교환 조건:</strong> 이름·번호 마킹 등 주문 제작을 선택하기 전에 해당 판매자의 교환 조건을 확인하세요.</li></ul>
<h2>자주 묻는 질문</h2><h3>S·M·L이나 지역별 사이즈를 바로 추천하나요?</h3><p>아니요. 아시아·US·EU 같은 지역 이름만으로 핏을 확정하지 않습니다. 상품의 실제 치수를 비교하는 도구입니다.</p><h3>상품에 의류 실측표가 없으면 어떻게 하나요?</h3><p>신체 치수표인지 먼저 확인하고, 의류 치수를 판매처에 문의하세요. 서로 다른 기준의 수치를 억지로 맞춰 입력하지 마세요.</p><h3>입력한 치수는 저장되나요?</h3><p>치수는 이 화면의 비교에만 사용하며 서버로 보내지 않습니다. 새로고침하면 입력을 다시 확인해야 합니다.</p><p><a href="/mag/jersey/">함께 읽기: 유니폼 구매 가이드</a></p>'''
best='''<h1>나만의 베스트11 메이커</h1><p class="lead">포메이션과 11명의 이름을 넣어 라인업을 만들고 PNG 이미지로 저장하세요. 입력한 명단을 무작위로 배치할 수도 있습니다.</p>
<section class="tool-panel" aria-labelledby="lineup-title"><h2 id="lineup-title">라인업 만들기</h2><form id="lineup"><div class="fields"><div class="field"><label for="formation">포메이션</label><select id="formation"><option>4-3-3</option><option>4-4-2</option><option>3-5-2</option><option>4-2-3-1</option></select></div><div class="field"><label for="team">팀 이름 (선택)</label><input id="team" maxlength="40" placeholder="예: 주말 축구 모임"></div></div><p class="hint">골키퍼부터 공격수 순서입니다. 이름이 빈 자리는 ‘선수 1’처럼 표시합니다.</p><div class="names" id="names"></div><div class="actions"><button type="submit">라인업 이미지 만들기</button><button id="example" type="button" class="secondary">예시 명단</button><button id="random" type="button" class="secondary">입력한 11명 섞기</button></div></form><p id="lineup-status" role="status"></p><canvas id="pitch" width="900" height="1200" hidden aria-label="입력한 이름으로 만든 베스트11 배치도"></canvas><a class="download" id="download" download="best11-chukguchanggo.png" hidden>PNG 이미지 저장</a></section>
<h2>명단을 공유하는 순서</h2><ol><li>팀의 기본 배치에 맞는 포메이션을 고릅니다. 골키퍼까지 합쳐 11자리입니다.</li><li>포지션 옆에 이름을 입력합니다. 팀 이름은 생략해도 됩니다.</li><li>미리보기에서 배치와 이름을 확인합니다. 긴 이름은 그림 안에 맞게 작게 표시됩니다.</li><li>PNG 이미지로 저장한 뒤 모임 공지나 자신의 게시물에 첨부하세요.</li></ol>
<h2>포메이션을 바꾸면 무엇이 달라지나요?</h2><p>4-3-3은 수비 4명·미드필더 3명·공격수 3명, 4-4-2는 수비 4명·미드필더 4명·공격수 2명을 표시합니다. 3-5-2에는 측면의 윙백을, 4-2-3-1에는 수비형 미드필더 2명과 공격형 미드필더 3명을 구분해 배치했습니다.</p><p>이름은 입력 순서대로 유지되므로 포메이션을 바꾼 뒤 각 선수의 자리를 다시 확인하세요. 왼쪽·오른쪽은 위쪽으로 공격하는 팀 기준입니다. 배치도는 기본 위치를 보여주며 경기 중 움직임이나 전술 효과를 예측하지 않습니다.</p>
<h2>랜덤 배정은 이렇게 쓰세요</h2><p>11명을 모두 입력한 뒤 ‘입력한 11명 섞기’를 누르면 입력한 사람들끼리 자리가 바뀝니다. 골키퍼 자리도 포함됩니다. 포지션 적성이나 실력을 반영하는 팀 편성 기능은 아니므로 놀이용 배치 후 필요한 자리는 직접 수정하세요.</p><div class="example"><p>모임에서 각자 한 명씩 이름을 정해 ‘우리의 베스트11’을 만들거나, 팀원 1~11이라는 예시 명단으로 먼저 배치를 시험해볼 수 있습니다. 실존 선수의 현재 소속이나 능력 데이터를 자동으로 불러오지는 않습니다.</p></div>
<h2>자주 묻는 질문</h2><h3>선수 사진이나 팀 엠블럼도 넣을 수 있나요?</h3><p>현재는 이름과 포지션을 표시하는 도구입니다. 사진이나 엠블럼을 불러오지 않아 명단 중심으로 간단하게 공유할 수 있습니다.</p><h3>명단은 저장되나요?</h3><p>입력한 이름은 서버로 전송되지 않습니다. 페이지를 닫기 전에 PNG를 저장하세요. 저장된 PNG는 이미지이므로 이름을 바꾸려면 이 도구에서 다시 만들어야 합니다.</p><h3>PNG는 어떻게 확인하나요?</h3><p>저장 버튼을 누른 뒤 브라우저의 다운로드 목록이나 기기의 파일 앱에서 확인하세요. 모바일에서는 브라우저에 따라 이미지 미리보기가 열릴 수도 있습니다.</p><p><a href="/tools/formation/">포메이션 뷰어</a> · <a href="/mag/glossary/">축구 용어 가이드</a></p>'''
balance='''<h1>축구 밸런스 게임 — 둘 중 하나를 고른다면?</h1><p class="lead">관전·동호회·응원팀·전술, 24개의 질문으로 축구 취향을 나눠보세요. 주제별로 6개씩 진행하거나 전체 질문을 즐길 수 있습니다.</p>
<section class="tool-panel" aria-labelledby="game-title"><h2 id="game-title">나의 축구 취향 고르기</h2><div class="field"><label for="category">질문 주제</label><select id="category"><option>전체</option><option>관전</option><option>동호회</option><option>응원팀</option><option>전술</option></select></div><p class="hint">주제를 바꾸거나 새 게임을 시작하면 지금 선택한 결과가 초기화됩니다.</p><p class="progress" id="progress" role="status"></p><div id="play"><p id="question"></p><div class="choice"><button id="choice-a" type="button"></button><button id="choice-b" type="button"></button></div></div><div id="summary" hidden><h3>이번 게임에서 고른 답</h3><ol id="history"></ol><button id="copy" type="button">결과 복사하기</button><p id="copy-status" role="status"></p><textarea id="copy-fallback" readonly hidden aria-label="복사할 선택 결과"></textarea></div><div class="actions"><button id="restart" type="button" class="secondary">새 게임 시작</button></div></section>
<h2>이렇게 즐겨보세요</h2><ol><li>모임 분위기에 맞는 주제를 정합니다. 전체는 24개, 각 주제는 6개입니다.</li><li>두 선택지 중 더 끌리는 하나를 고릅니다. 같은 게임 안에서는 질문이 반복되지 않습니다.</li><li>함께 한다면 서로의 선택 이유를 한 문장씩 이야기해보세요.</li><li>마지막에 자신의 선택을 모아서 보고 복사할 수 있습니다.</li></ol><h2>질문과 대화의 예시</h2><div class="example"><p><strong>골대 뒤 응원석 vs 하프라인 근처 관람석</strong><br>“나는 함께 응원하는 분위기가 좋아서 골대 뒤.”<br>“나는 선수들의 전체 움직임을 보고 싶어서 하프라인 근처.”</p></div><p>같은 경기를 좋아해도 즐기는 방식은 다를 수 있습니다. 상대의 선택을 평가하기보다 왜 골랐는지 물어보면 대화가 이어집니다. 정답이나 축구 지식 점수는 없습니다.</p><h2>주제별로 어떤 질문이 나오나요?</h2><ul><li><strong>관전:</strong> 직관과 집관, 좌석, 경기장에 머무는 시간.</li><li><strong>동호회:</strong> 포지션, 팀 역할, 패스와 득점의 취향.</li><li><strong>응원팀:</strong> 감독, 우승의 순간, 응원하는 팀의 이야기.</li><li><strong>전술:</strong> 압박, 역습, 빌드업처럼 경기를 보는 취향.</li></ul><h2>자주 묻는 질문</h2><h3>다른 사람의 선택 비율도 나오나요?</h3><p>이 도구는 투표를 수집하지 않습니다. 표시하는 결과는 이번 게임에서 내가 선택한 답이며, 전체 이용자의 인기 순위나 선택 비율이 아닙니다.</p><h3>질문이 다시 나올 수도 있나요?</h3><p>한 게임에서는 각 질문을 한 번만 보여줍니다. 새 게임을 시작하면 순서를 다시 섞으며, 이전 게임에 있던 질문은 다시 나올 수 있습니다.</p><h3>결과가 내 축구 성향을 진단하나요?</h3><p>아니요. 대화를 위한 가벼운 선택 게임이며 능력이나 성격을 판단하지 않습니다. 선택 내용은 서버로 보내지 않습니다.</p><p><a href="/tools/best11/">다음 놀이: 우리 모임 베스트11 만들기</a> · <a href="/mag/glossary/">낯선 축구 용어 살펴보기</a></p>'''
for slug,title,desc,body in [('uniform','유니폼 사이즈 비교 — 내 옷 실측으로 확인하기','의류 가슴 단면과 총장을 입력해 내 옷과 구매할 유니폼의 실측 차이를 비교하세요.',uniform),('best11','베스트11 메이커 — 포메이션·랜덤 배정·PNG 저장','11명의 이름으로 라인업을 만들고 이미지로 저장하세요. 입력 명단 무작위 배정도 가능합니다.',best),('balance-game','축구 밸런스 게임 — 24개 질문과 선택 결과','관전·동호회·응원팀·전술 질문을 중복 없이 즐기고 나의 선택을 모아 복사하세요.',balance)]:
 url=f'https://chukguchanggo.com/tools/{slug}/'
 data={'@context':'https://schema.org','@type':'WebApplication','name':title,'url':url,'description':desc,'applicationCategory':'SportsApplication','operatingSystem':'Web','offers':{'@type':'Offer','price':'0','priceCurrency':'KRW'}}
 doc=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(title)} | 축구창고</title><meta name="description" content="{html.escape(desc)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{html.escape(title)}"><meta property="og:description" content="{html.escape(desc)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><meta property="og:image" content="https://chukguchanggo.com/og-image-v2.png"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/internal.css?v=0908-review1"><link rel="stylesheet" href="/tools/experience.css?v=0910-1"><script type="application/ld+json">{json.dumps(data,ensure_ascii=False)}</script><script async src="https://www.googletagmanager.com/gtag/js?id=G-TKC505GRGB"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','G-TKC505GRGB');</script></head><body class="sg-static" data-tool="{slug}"><header class="hd"><a href="/">축구창고</a><div class="sub">축구를 즐기는 도구와 이야기</div></header><main class="wrap"><p class="meta"><a href="/tools/">축구 도구</a> · 무료 · 가입 없음</p>{body}<noscript><p>도구를 사용하려면 브라우저에서 JavaScript를 켜주세요. 사용 방법은 이 페이지에서 읽을 수 있습니다.</p></noscript><p class="hint">안내 업데이트: 2026년 9월 10일</p></main><footer class="ft"><a href="/about.html">소개</a> · <a href="/contact.html">문의</a> · <a href="/privacy.html">개인정보처리방침</a><p>© 축구창고</p></footer><script src="/internal.js?v=0908-review1"></script><script src="/tools/experience.js?v=0910-1"></script></body></html>'''
 (SOURCE/(slug+'.html')).write_text(doc,encoding='utf-8')
 for base in [ROOT,ROOT/'homepage-refresh']:
  target=base/'tools'/slug/'index.html';target.parent.mkdir(parents=True,exist_ok=True);target.write_text(doc,encoding='utf-8')
for asset in ['experience.js','experience.css']:
 for base in [ROOT,ROOT/'homepage-refresh']:(base/'tools'/asset).write_bytes((SOURCE/asset).read_bytes())
print('Generated three tool experiences and shared assets')
